apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-nginx
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: nginx
        namespace: default
        repoURL: git@github.com:sahar449/argo_test.git
        path: .
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.defaulta.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
